name = "moonpiece-homepage"
main = "index.js"
compatibility_date = "2024-04-03"

[site]
bucket = "./"
exclude = ["node_modules", ".git", "functions"]

[[r2_buckets]]
binding = "JOURNAL_BUCKET"
bucket_name = "moonpiece-journal"

[ai]
binding = "AI"
